Private repos
tranquilitybase-io/tb-gcp-dac pull request #188
Opened 2020-12-04 11:15 UTC by aivogft

test complete

2020-12-04 13:56 UTC, Salles-FA requested changes
Please fix the Codacy issue

2020-12-08 20:44 UTC, Salles-FA commented
https://github.com/tranquilitybase-io/TranquilityBase/issues/66

2020-12-08 21:00 UTC, Salles-FA requested changes

2020-12-08 21:00 UTC, Salles-FA commented on gcpdac_tests/gcp_tests/test_onboarding.py
> +    #git clone --progress -v https://aivogft:a2a0076e37f41f706c052ccef1e15a81c5987f19@github.com/tranquilitybase-io/gcp-citrix-activator.git
@aivogft, I'm sure you have already revoked this token. Please remove from the code. Thx!

2020-12-08 21:01 UTC, Salles-FA commented
![image](https://user-images.githubusercontent.com/5604834/101540882-6bf85a00-397f-11eb-86eb-d69a0512d5a3.png)

2020-12-09 11:26 UTC, sunderhill-gft approved these changes
Looks good

2020-12-09 13:04 UTC, Salles-FA approved these changes

2020-12-09 13:04 UTC, merged